service: example
 
provider:
  name: aws
  runtime: python3.8
 
plugins:
  - serverless-wsgi
  - serverless-python-requirements
 
functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
 
custom:
  wsgi:
    app: api.app
    pythonBin: python3.8
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
