version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0
  serverless: circleci/serverless-framework@1.0

jobs:
  deploy:
    executor:
      name: serverless/default
      python-version: 3.8-node
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup
      - run: sls plugin install -n serverless-wsgi@1.7.8
      - run: sls plugin install -n serverless-python-requirements
      - run: sls package --stage dev --verbose

workflows:
  main:
    jobs:
      - deploy
