version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0

commands:
  diagnose:
    steps:
      - run: echo $PATH
      - run: which python3.8
      - run: |
          # calling python3.8 here works
          python3.8 -c "print(1)"

jobs:
  deploy:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - aws-cli/setup
      - run: npm install serverless
      - run: |
          npx sls --version
      - run: npm install serverless-wsgi@1.7.8
      - run: npm install serverless-python-requirements
      - run: |
          SLS_DEBUG=* npx sls package --stage dev

workflows:
  main:
    jobs:
      - deploy
