version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0
  serverless: circleci/serverless-framework@1.0

jobs:
  deploy:
    executor:
      name: serverless/default
      python-version: 3.8-node
    steps:
      - checkout
      - run: |
          sls --version
      - run: |
          echo $PATH

          which python3.8
      - run: |
          # calling python3.8 here works
          python3.8 -c "print(1)"
      - aws-cli/setup
      - serverless/setup
      - run: sls plugin install -n serverless-wsgi@1.7.8
      - run: sls plugin install -n serverless-python-requirements
      - run: |
          SLS_DEBUG=* sls package --stage dev

workflows:
  main:
    jobs:
      - deploy
